import contextlib
from typing import Any

class record_function(contextlib.ContextDecorator):
    def __init__(self, name: str) -> None: ...
    def __enter__(self) -> Any: ...
    def __exit__(self, *exctype: Any) -> None: ...
